on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: rdp-duty-machine/rdp-duty-machine-action@master
        env:
          TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
